### ISSUE TITLE
Practica_Architec_Genaro Santiago Valentín

### ISSUE THREAD

**Issue by Valentiin01** [SistemasTecTlaxiaco/actividad-3-practica-architect-Valentiin01#1]
[Actividad3_Practica.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-practica-architect-Valentiin01/files/9492202/Actividad3_Practica.pdf)

**Comment by ang3-l32** [comment]
calificación;19

**Comment by josealfredo79** [comment]
Bien hecho y revisado
